type Query {
    me: User
    getUserDetails(user_id: String!): User
    getProjectDetails(project_id: String!): Project
    listProjectMembers(project_id: ID!): [ProjectMember]
}

type Mutation {
    register(email: String!, password: String!): AuthPayload
    login(email: String!, password: String!): AuthPayload
}

type User {
    id: ID!
    email: String!
}

type AuthPayload {
    token: String!
    user: User!
}

extend type Mutation {
    createProject(name: String!): Project!
    inviteUserToProject(project_id: ID!, user_id: ID!, role: String!): Boolean
}

type Project {
    id: ID!
    name: String!
    owner_id: ID!
}

type ProjectMember {
    id: ID!
    user: User!
    project: Project!
    role: String!
}